Google Drive Add
patheticGeek/torrent-aio-bot pull request #103
Opened 2021-05-19 09:23 UTC by Himusaki

Can u add me to your google Shared drive ?
farukimatona@gmail.com

2021-05-19 10:56 UTC, patheticGeek requested changes
This is a good PR, just do the two changes and I'll merge.
Appreciate the time you put in :+1:

2021-05-19 10:56 UTC, patheticGeek commented on Readme.md
> +[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/sobuj53/torrent-aio-bot)
This commit doesn't need to be in this merge

2021-05-19 10:56 UTC, patheticGeek commented on lib/bot.js
> +        //mess1 += `Download Link 🔗: ${torr.downloadLink}\n\n`;
Keep the direct link for if the user wants to stream

2021-05-19 10:57 UTC, patheticGeek commented
> Can u add me to your google Shared drive ?
> [farukimatona@gmail.com](mailto:farukimatona@gmail.com)

My shared drive is fked, not using it anymore as downloads and streams are blocked

2021-05-23 12:03 UTC, sobuj53 commented
I think the user must have created this pr by mistake. My repo is almost in full sync with your reop. Those are just few changes that are very custom to my likings. In short you can close this pr. Thank you for your awesome repo.

2021-05-23 18:46 UTC, closed without merging